name: choco_lyrics
description: "An app that let you explore the lyrics of songs"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.7
  flutter_bloc: ^8.1.6
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
